/*
 * current_sensor_parameter.h
 *
 *  Created on: Feb 18, 2025
 *      Author: TerenceLeung
 */

#ifndef APPLICATION_MOTOR_SENSORS_BATTERY_CURRENT_SENSOR_PARAMETER_H_
#define APPLICATION_MOTOR_SENSORS_BATTERY_CURRENT_SENSOR_PARAMETER_H_

#define SHUNT_RESISTANCE    0.005
#define CURRENT_GAIN        25

#endif /* APPLICATION_MOTOR_SENSORS_BATTERY_CURRENT_SENSOR_PARAMETER_H_ */
